### ISSUE TITLE
Lib suggestion

### ISSUE THREAD

**Issue by vortigont** [strange-v/PowerMonitor#1]
Hi! That's a nice project indeed, mostly based on RTOS features instead of arduino loop() - like it!
Just wanted to give you a hint on my lib [pzem-edl](https://github.com/vortigont/pzem-edl), I made one to deal with PZEM's using rtos-based approach to a non-blocking IO. You might wanna take a look, would appreciate any feedback.
Cheers!

**Comment by strange-v** [comment]
Hi, thanks.
Probably, I'll experiment with this library in case of creating a new module with 3 PZEM devices, as it has no sense for the current one.

**Comment by vortigont** [comment]
Sure!
btw, it also has ring buffers for time-series data, implemented but no example yet. Pretty easy to make some in-memory time-series data and charts, i.e. looks like [this](https://github.com/vortigont/espem)
